server:
    port: 8080
    contextPath: /client


config:
    oauth2:
        clientID: confidential
        clientSecret: secret
        accessTokenUri: http://localhost:9999/uaa/oauth/token
        userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
        resourceURI: http://localhost:9000/api/

security:
  basic:
    enabled: false
#  oauth2:
#    client:
#      clientID: confidential
#      clientSecret: secret
#      accessTokenUri: http://localhost:9999/uaa/oauth/token
#      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
